name = "ezsolvy-api"
main = "backend/apps/api-worker/src/index.ts"
compatibility_date = "2024-01-01"

[env.production]
name = "ezsolvy-api-prod"
route = { pattern = "api.ezsolvy.com/*", zone_name = "ezsolvy.com" }

[env.staging]
name = "ezsolvy-api-staging"
